### PR TITLE
[don't merge] PR to track SmartTub changes that aren't merged into dev yet

### PR DESCRIPTION
**Pull request by mdz**

### CODE REVIEW

**Comment by mdz** [comment]
@shaun-hope @curt7000 at this point, all of the basics are merged into dev:

- thermostat
- sensors
- pumps
- lights

It would be great if you could give it a whirl and let me know how it works for you!

Next on my list is adding services so that you can change the configuration settings

**Comment by mdz** [comment]
@shaun-hope @curt7000 these features are included in https://rc.home-assistant.io/blog/2021/02/24/release-20213/ . I would greatly appreciate if you could test, especially setting up the integration, to make sure it works with your equiment as well. Thanks!

**Comment by curt7000** [comment]
> @shaun-hope @curt7000 these features are included in https://rc.home-assistant.io/blog/2021/02/24/release-20213/ . I would greatly appreciate if you could test, especially setting up the integration, to make sure it works with your equiment as well. Thanks!

Installed.  Really great work getting this into Core so quickly!

General status details are working.  No issues.

Climate is working.  No issues.

Lighting is working.  On/Off and brightness works.  Status is super slow, but this is a limitation of the controller and cellular network.

Pumps are semi-working.  I was able to turn P1 & P2 on, but then turning them off was a bit hit or miss.  I encountered failed service calls and the Pump status seemed to never reflect the actual state of the pumps.  After a few tries I was able to get P1 and P2 to turn off.

I think I saw from a prior post that pumps are toggle only.  Perhaps the on/off switch status is causing problems due to the delay?

I also noticed that although Lovelace reported the switch as On, the switch details reported it as Off.  See attached picture.
IMG_1804
IMG_1803

**Comment by mdz** [comment]
Thanks so much for testing! Glad to hear that things mostly worked for you.

> Lighting is working. On/Off and brightness works. Status is super slow, but this is a limitation of the controller and cellular network.

Yes, the polling is currently set to 60 seconds. I'm pretty sure the vendor app polls more frequently than this, so we can probably shorten it, but I wanted to start conservatively because I don't know what rate limits etc. might exist and don't want to get HA blocked from the API. If you want to experiment with different values for `SCAN_INTERVAL`, let me know what you learn.

> Pumps are semi-working. I was able to turn P1 & P2 on, but then turning them off was a bit hit or miss. I encountered failed service calls and the Pump status seemed to never reflect the actual state of the pumps. After a few tries I was able to get P1 and P2 to turn off.
> 
> I think I saw from a prior post that pumps are toggle only. Perhaps the on/off switch status is causing problems due to the delay?

Yes, it can be a bit fiddly. I see the same behavior with other cloud polling integrations, so it may not be the integration's fault. But I did make one fix to the pump switches which might be relevant: https://github.com/home-assistant/core/pull/47184

I had implemented `turn_on` and `turn_off` actions which toggled based on the current state. This PR removes those and lets the light platform deal with this, exposing only a toggle. It may not make any difference, I haven't tried to reproduce your issue yet.

> 
> I also noticed that although Lovelace reported the switch as On, the switch details reported it as Off. See attached picture.
> IMG_1804
> IMG_1803

Strange, I have no idea what's going on there. As soon as the API call to toggle the switch returns, we schedule an immediate poll to update the state. As long as the API provides some consistency, the state should update immediately, but I have seen delays. I haven't tried to diagnose the issue yet.

Thanks again for testing and keep the feedback coming!

**Comment by curt7000** [comment]
Everything went unavailable. 🙁

I’ll send you logs separately.

**Comment by curt7000** [comment]
here are the errors:
============================================================
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smarttub/switch.py:81 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 4:05:29 PM (1 occurrences) 
Last logged: 4:05:29 PM

[140184337518352] 500, message='Internal Server Error', url=URL('https://api.smarttub.io/spas/MYSERIAL/pumps/P1/toggle')
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 111, in request
    r.raise_for_status()
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.smarttub.io/spas/MYSERIAL/pumps/P1/toggle')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/switch.py", line 69, in async_turn_on
    await self.async_toggle()
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/switch.py", line 81, in async_toggle
    await self.pump.toggle()
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 380, in toggle
    await self.spa.request("POST", f"pumps/{self.id}/toggle")
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 175, in request
    return await self._api.request(method, f"spas/{self.id}/{resource}", body)
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 113, in request
    raise APIError(e)
smarttub.api.APIError: 500, message='Internal Server Error', url=URL('https://api.smarttub.io/spas/MYSERIAL/pumps/P1/toggle')

==================================================================

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smarttub/switch.py:81 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 4:05:52 PM (2 occurrences) 
Last logged: 4:06:18 PM

[140184337518352]
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/switch.py", line 81, in async_toggle
    await self.pump.toggle()
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 380, in toggle
    await self.spa.request("POST", f"pumps/{self.id}/toggle")
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 175, in request
    return await self._api.request(method, f"spas/{self.id}/{resource}", body)
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 106, in request
    r = await self._session.request(
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/switch.py", line 69, in async_turn_on
    await self.async_toggle()
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/switch.py", line 81, in async_toggle
    await self.pump.toggle()
  File "/srv/homeassistant/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/srv/homeassistant/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

================================================================

**This one shows up 134 times since 16:00EST**

Logger: custom_components.smarttub.controller
Source: custom_components/smarttub/controller.py:89 
Integration: SmartTub (documentation) 
First occurred: 6:59:04 PM (134 occurrences) 
Last logged: 9:12:04 PM

Unexpected error fetching smarttub data: 'FULL_DYNAMIC_RGB'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
    return await self.update_method()
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/controller.py", line 82, in async_update_data
    data[spa.id] = await self._get_spa_data(spa)
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/controller.py", line 89, in _get_spa_data
    status, pumps, lights = await asyncio.gather(
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 188, in get_lights
    return [
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 189, in <listcomp>
    SpaLight(self, **light_info)
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 403, in __init__
    self.mode = self.LightMode[properties["mode"]]
  File "/usr/lib/python3.8/enum.py", line 349, in __getitem__
    return cls._member_map_[name]
KeyError: 'FULL_DYNAMIC_RGB'

**Comment by mdz** [comment]
Thanks @curt7000. I see two issues there:

1. A 500 error from the smarttub API. I'm not sure what's going on there,
since you said the same call was working previously. That endpoint doesn't
take any parameters, so I can't think of what could be wrong on our end.
I'll take a closer look later this week. Please open an issue on the HA
core repo (and assign to me if you can).

2. Your unit apparently has a color mode that mine doesn't. This is easily
fixed in python-smarttub by adding a member to the enum. I'll fix that now
and cut a new release.

**Comment by mdz** [comment]
By the way, you should be able to work around issue #2 by changing the
light mode on your unit to one of the supported values. The error occurs
when we're reading the state of the light and it returns an unknown mode.

**Comment by mdz** [comment]
Ah, I see there's a third issue there, which is a timeout. I'm also not
sure what's causing that one. Both that and the 500 error seem like the
SmartTub API misbehaving, but I'm not seeing any failures on my own setup.

**Comment by curt7000** [comment]
Updated sensor.py, will report back tomorrow evening.

**Comment by curt7000** [comment]
Are you seeing similar status history for the Online binary sensor?  Does it make sense to remove it to reduce chatter/logging?

image

**Comment by mdz** [comment]
Yes, I see a similar pattern with that sensor. There should be no logs
though (I don't see any). You can disable the entity if you don't find it
useful. I'll probably disable some of them by default in a future release.

I assumed that this sensor would track whether the unit had a working data
connection, but it seems to mean something else.

**Comment by curt7000** [comment]
The state probably indicates when the Jacuzzi checks in over cellular.

I will probably disable it.  But, one idea I have may be to write an
automation to trigger, if the state hasn't changed in 24hrs, with a push
notification action to suggest the connection is broken.  Then again, I
have too many push notifications already! :)

**Comment by curt7000** [comment]
Just checked and it all entities went unavailable again.  I haven't made any changes or interacted with the Jacuzzi.

Two errors:

================================================
Logger: custom_components.smarttub.controller
Source: custom_components/smarttub/controller.py:89 
Integration: SmartTub (documentation) 
First occurred: 6:58:51 PM (143 occurrences) 
Last logged: 9:20:51 PM

Unexpected error fetching smarttub data: 'FULL_DYNAMIC_RGB'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
    return await self.update_method()
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/controller.py", line 82, in async_update_data
    data[spa.id] = await self._get_spa_data(spa)
  File "/home/homeassistant/.homeassistant/custom_components/smarttub/controller.py", line 89, in _get_spa_data
    status, pumps, lights = await asyncio.gather(
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 188, in get_lights
    return [
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 189, in <listcomp>
    SpaLight(self, **light_info)
  File "/srv/homeassistant/lib/python3.8/site-packages/smarttub/api.py", line 403, in __init__
    self.mode = self.LightMode[properties["mode"]]
  File "/usr/lib/python3.8/enum.py", line 349, in __getitem__
    return cls._member_map_[name]
KeyError: 'FULL_DYNAMIC_RGB'

================================================

Logger: custom_components.smarttub.controller
Source: helpers/update_coordinator.py:153 
Integration: SmartTub (documentation) 
First occurred: 6:10:49 PM (1 occurrences) 
Last logged: 6:10:49 PM

Timeout fetching smarttub data

**Comment by mdz** [comment]
That will continue to happen every time the light mode is changed to that
setting, until you upgrade to python-smarttub==0.0.19

**Comment by curt7000** [comment]
weird ... I thought I upgraded to 0.19.  I went to the
python-smarttub repository on Git and updated the api.py file.  Or is there
another way?  I'm in a VENV, Python 3.8, Ubuntu.

**Comment by mdz** [comment]
Hard to say what went wrong, but you might try installing it with pip
rather than patching the files by hand.

`pip install python-smarttub==0.0.19` after activating your venv should do
the trick.

You should be able to verify it like this:

```
Python 3.9.2 (default, Feb 19 2021, 17:43:04)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import smarttub
>>> smarttub.SpaLight.LightMode["FULL_DYNAMIC_RGB"]
<LightMode.FULL_DYNAMIC_RGB: 9>
>>>
```

If you try that on 0.0.18 or earlier, you'll get the `KeyError` you've been
seeing.

**Comment by curt7000** [comment]
Ok, got it updated.  It was showing as unavailable last night, but this morning, it started working.  One thing of concern, my SmartTub app will not login, stating that the Tub is offline.  I've never had that before.  I've deleted the integration and am waiting to see if I can reconnect with the official app.

**Comment by mdz** [comment]
When it was showing as unavailable last night, did you see errors in the
log?

**Comment by curt7000** [comment]
just the same errors I saw previously.

**Pull request closed without merging**
